from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from pprint import pprint
from datetime import datetime
import pandas as pd
from pandas.stats.moments import ewma
import numpy as np
import sys
import json
from pprint import pprint

import urllib2
url_source_code = "https://raw.githubusercontent.com/biwa7636/inventory/master/poolOfFunctions/bafuns.py"
code = urllib2.urlopen(url_source_code).read()
exec(code)

@csrf_exempt
def index(request):
# The json data has to be valid JSON that generated by DataFrame.to_json
# where contains at least two columns 'ingestdate' like '20010203', and 'qtyavail', like '123456'
    try:
        data = json.loads(request.body)
        myfunction = data['function']
        df = pd.read_json(data['data'])
        result = globals()[myfunction](df)
        return HttpResponse(json.dumps(result))
    except: 
        return HttpResponse(json.dumps({'status':'fail', 'reason':sys.exc_info()}), content_type="application/json")
