from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from pprint import pprint
from datetime import datetime
import pandas as pd
from pandas.stats.moments import ewma
import numpy as np
import sys
import json
from pprint import pprint

import urllib2
url_source_code = "https://raw.githubusercontent.com/biwa7636/inventory/master/poolOfFunctions/bafuns.py"
code = urllib2.urlopen(url_source_code).read()
exec(code)


@csrf_exempt
def index(request):
# The json data has to be valid JSON that generated by DataFrame.to_json
# where contains at least two columns 'ingestdate' like '20010203', and 'qtyavail', like '123456'
    try:
        print 'working'
        data = dict(request.POST)
        myfunction = data['function'][0]
        mydata = data['data']
        print myfunction
        print mydata
        print data
        print globals()[myfunction]
        return HttpResponse('Working')
        """
        df = pd.read_json(request.body)
        # TODO - need to pull the function from git dynamically
        # where the code is unit tested
        df['ingestdatetime'] = df.apply(lambda row: datetime.strptime(str(row['ingestdate']), "%Y%m%d"), axis=1)
        df = df.sort(['ingestdate'], ascending=[1])
        df['qtyavail_ewma'] = ewma(df['qtyavail'], span=50)
        s, b = myfunc_buy_sale(df['qtyavail_ewma'])
        result = {'status':'success', 'sell':s, 'buy':b}
        return HttpResponse(json.dumps(result), content_type="application/json")
        """
    except: 
        return HttpResponse(json.dumps({'status':'fail', 'reason':sys.exc_info()}), content_type="application/json")
